### ISSUE TITLE
Submodel Aggregator does not support multiple Submodels with same idShort

### ISSUE THREAD

**Issue by ipamaas** [eclipse-basyx/basyx-java-sdk#47]
An AAS Server is able to serve multiple shells. Each shell can have multiple submodels.

As the ``Submodel Aggregator`` is currenlty holding the ``Submodel APIs`` in a Map with ``idShort`` as key, all Submodel Apis based on same idShort will overwrite each other and only one will be left serving for all other. The AAS Server will serve the wrong Submodel in this case for all but one of these Submodels.

It is very likely on larger AAS Server instances, that there are equal idShorts used, so it would be better to use the identifier.id instead.

How to reproduce:
1. Setup AAS Server with MongoDB as backend
1. Add two different AAS
1. For each AAS, add a Submodel with different Identifier but same idShort
1. Run AAS Server
1. Call both AAS (should be working)
1. Call both Submodels (only one of the Submodel is serverd for both calls)

Possible solution:
Refactor ``SubmodelAggregator`` to use Identifier instead of idShort e.g. here ...
```java
smApiMap.put(submodelAPI.getSubmodel().getIdShort(), submodelAPI);
```
use identifier ...
```java
smApiMap.put(submodelAPI.getSubmodel().getIdentification().getId(), submodelAPI);
```
as it is already done on the AAS Aggregators level e.g. in ``MongoDbAASAggregator`` for the aasProviderMap:
```java
aasProviderMap.put(aas.getIdentification().getId(), provider);
```
Basyx Version: ``1.1.0-SNAPSHOT``

BR Matthias

**Comment by FrankSchnicke** [comment]
Many thanks for pointing this out and also suggesting a solution. However, changing this behavior would change the HTTP/REST API and thus introduce a breaking change. In consequence, this is something that we can't address before the 2.0.0 release.

Nevertheless, this issue will most likely not pop up for our off-the-shelf-components. Each AAS is assigned its own SubmodelAggregator. In consequence, the idShort only has to be unique within the scope of a single AAS.

**Comment by ipamaas** [comment]
Thanks for the quick reply. 
But it think it is also an issue for off-the-shelf-components (at least in the current 1.1.0-snapshot), if e.g. using the ``MongoDbAASAgregator``.

The ``SubmodelAggregaotr`` is instantiated once in the constructor here and same instance used for all ``MultiSubmodelProvider``.
This is why the issue also is reproducable with the AAS Server commponent with MongoDB Backend in 1.1.0-SNAPSHOT.

**Comment by ipamaas** [comment]
So it is more an issue of how the ``SubmodelAggregator`` is instantiated (also in the off-the-shelf components). If instantiated per provider, it may not be neccessary to change from idShort to identifier.id, as within the same AAS context it is much easier to prevent using the same idShort several times.

**Comment by FrankSchnicke** [comment]
Fixed, for details see linked PR. Many thanks again for pointing this out & providing a PR.

**Comment by ipamaas** [comment]
Tested with the updated 1.1.0-SNAPSHOT.
It is still a reproducable issue and not fixed yet.
The ``SubmodelAggregaotr`` is still instantiated once in the constructor of ``MongoDbAASAgregator`` and same instance used for all MultiSubmodelProvider. If different AAS using a Submodel with same idShort, only one is served for all!

**Comment by FrankSchnicke** [comment]
That's rather strange - thanks for making me aware of this issue still being there. We will further investigate and provide a fix.

**Comment by ipamaas** [comment]
Does it help if I add a new Test in ``TestMongoDBAggregator`` to demonstrate it, and send it as PR?

**Comment by FrankSchnicke** [comment]
This would be great

**Comment by FrankSchnicke** [comment]
Will be fixed when https://github.com/eclipse-basyx/basyx-java-components/pull/83 is merged. Many thanks again!

**Comment by FrankSchnicke** [comment]
Merged & Fixed.
